name: Insta_Tracker

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
      REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
      REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
      REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
      REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
      REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      # - name: Run unit tests
      #   run: yarn test:unit
      - name: Generate build
        run: yarn build
      # - name: Run E2E tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     start: yarn start:build
      # Deploy artifact to firebase hosting
      - name: Create firebase preview link
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_INSTATRACKER }}"
          channelId: live
          projectId: instatracker-2a0fd

