name: Insta_Tracker_PR_Preview

"on": pull_request

jobs:
  build:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      # - name: Run unit tests
      #   run: yarn test:unit
      - name: Generate build
        run: yarn build
      # - name: Run E2E tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     start: yarn start:build
      # Deploy artifact to firebase hosting
      - name: Create firebase preview link
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_INSTATRACKER }}"
          projectId: instatracker-2a0fd

